### ISSUE TITLE
Share text improvements

### ISSUE THREAD

**Issue by vegeta897** [flippin-dev/flippin#1]
I think it would be interesting if the share text included the number of flips used to reach the solution. This would reduce focus on speed and reward players that want to take their time to carefully consider each move. I think the balance between time and flips would add a good meta-layer to how players gauge their own performance each day.

I also encourage you to include the game's URL so it's easier for others to get on board!

And by the way, thank you for acknowledging the inspiration from Word Peaks, it made me really happy to read that. I hope my code wasn't too painfully messy. What you've made is wonderful! I especially like the color themes.

**Comment by flippin-dev** [comment]
I agree with your proposals! I think incorporating the number of moves used and number of resets used would be interesting. The URL addition is also a good idea!

You are also welcome for the acknowledgment! Your project was incredibly useful as a reference point and made my life a lot easier on many occasions.
