### ISSUE TITLE
[BUG] Reset icon doesn't appear in Safari

### ISSUE THREAD

**Issue by flippin-dev** [flippin-dev/flippin#4]
**Describe the bug**
The icon used for the reset button does not appear when the game is played in the Safari browser.

**Reproduction**
1. Open Flippin in Safari
2. Navigate to main screen
3. See reset icon is missing

**Expected behavior**
Reset icon should be visible like other icons are.

**Device:**
 - OS: iOS
 - Browser: Safari

**Additional context**
This is likely due to the SVG used for that icon not having height and width set. I believe this defaults to auto in other browsers but not in Safari.

**Comment by vegeta897** [comment]
This should be solved by adding `width` and `height` attributes to the SVG.
